In [4]:
import pandas as pd
df=pd.read_csv("mumbai_weather.csv")
df.head(30)

     Temp     RH    WS      WD      SR
0   30.63  57.08  0.36   192.4  126.21
1   30.32  54.63  0.24  175.27  122.08
2   29.14  55.54  0.13  165.14  131.91
3   28.62  49.24  0.37  185.21  121.58
4   28.42  49.16  0.09  158.78  126.84
5   28.81  62.53  0.09  113.06  129.13
6   30.01  67.53  0.13  173.61  108.35
7   30.18  71.89  0.13  123.13  121.67
8   30.68  68.42  0.15  147.38  124.39
9   30.57  68.53  0.13  138.03   109.5
10  30.27  70.38  0.12  152.28  105.55
11  29.55  68.68  0.09  129.94  100.42
12  29.07  63.55   0.1  154.12   99.22
13  28.48  68.95   0.1  160.44  115.28
14  28.25  72.65  0.09  116.45  111.14
15  28.55  63.15  0.09  116.86  123.32
16  27.92  63.84  0.09  113.01  104.94
17  28.28  67.09   0.1   85.54   89.62
18  28.49  65.75  0.09  122.29   99.43
19  29.22  50.21  0.18  174.08  112.09
20   29.1  53.99  0.16  114.98   89.99
21  29.88  62.59  0.18  206.29  121.92
22   None   None  None    None    None
23   31.5  66.74   0.1   100.3   93.72
24  29.48  70.71  0.12  117.28   92.73
25  29.05   60.5  0.14  122.48   94.99
26   28.2  59.52   0.1  181.45  108.19
27  28.09  60.49   0.1  131.32  106.19
28  27.98  53.19   0.1  196.57  109.45
29  28.57  52.08  0.18  148.65  104.64

In [19]:
df['Temp']=df['Temp'].fillna(df['Temp'].mean())
df.head(30)

TypeError: Could not convert 30.6330.3229.1428.6228.4228.8130.0130.1830.6830.5730.2729.5529.0728.4828.2528.5527.9228.2828.4929.2229.129.88None31.529.4829.0528.228.0927.9828.5728.4929.2729.7927.3827.2926.6925.4426.5426.9129.1227.6528.3427.5627.3326.3125.8128.5627.8428.4627.224.8123.9724.7227.0127.9126.8525.4425.6325.5925.4226.5527.0127.328.6128.8929.1328.3927.1825.9225.6126.2426.9127.3227.1625.9825.7426.9827.3224.8824.424.0224.0724.4325.8225.7927.5829.1428.126.9426.6427.1528.828.327.7126.5526.926.8126.8626.9326.61NoneNoneNoneNoneNoneNoneNoneNoneNone29.7928.8729.833030.1529.8929.7529.8829.928.8329.3528.6828.96NoneNoneNoneNoneNoneNoneNoneNoneNoneNoneNoneNoneNoneNone31.8932.5334.7433.5630.830.5729.7129.3930.1730.0829.3930.2430.3431.2531.0330.3130.2230.130.7431.8532.1231.9731.4930.6930.9631.9431.4431.1630.8531.2531.3930.8932.1332.3132.0731.8832.0950.0754.1847.557.7657.9NoneNone57.9None57.957.9NoneNone57.9None57.9None57.957.957.9None57.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.950.1457.952.7557.957.957.957.957.957.957.957.944.431.4332.232.232.2330.342.5557.957.957.957.4355.3648.1456.2951.783.843.852.1413.6625.214.2920.5729.0329.0329.0327.328.3826.3120.9720.3145.9426.7522.4526.5726.6626.4726.7526.7526.755557.957.957.6547.0344.5356.2539.2630.330.326.1810.9514.1757.944.8121.9726.2321.335.335.335.332.7430.330.330.330.330.330.330.330.330.330.3NoneNoneNoneNoneNoneNone57.957.957.957.947.6832.332.332.332.332.332.332.332.332.332.332.335.8830.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.130.146.3457.957.957.957.957.957.957.9NoneNoneNoneNoneNoneNoneNone27.0526.7526.7526.7526.7526.7526.7535.9557.5853.9457.1357.951.3757.957.957.957.957.955.7457.952.1455.0557.957.957.957.957.9157.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.957.9 to numeric